### ISSUE TITLE
Errors to fix

### ISSUE THREAD

**Issue by tusbar** [geodatagouv/link-proxy#67]
- [x] **path must be a string or Buffer**
 http://geoservices.lorient-agglo.fr/documents/ref_bathymetrie/plages/pdf/25985_Cap-Lorient_Groix_BAT_01.pdf

 ```
  TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:636:11)
    at ReadStream.open (fs.js:1991:6)
    at new ReadStream (fs.js:1978:10)
    at fs.createReadStream (fs.js:1931:10)
    at uploadSingle (/Users/tusbar/dev/inspireteam/link-proxy/jobs/check/upload.js:36:37)
    at upload (/Users/tusbar/dev/inspireteam/link-proxy/jobs/check/upload.js:87:12)
    at Bluebird.map (/Users/tusbar/dev/inspireteam/link-proxy/jobs/check/index.js:155:38)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 ```

- [ ] **operation timed out**
 https://geobretagne.fr/pub/ddtm-29/doc-urba/
 https://geobretagne.fr/pub/ddtm-29/pva-1978-29/

 ```
  TimeoutError: operation timed out
    at afterTimeout (/Users/tusbar/dev/inspireteam/link-proxy/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/tusbar/dev/inspireteam/link-proxy/node_modules/bluebird/js/release/timers.js:76:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
 ```

**Comment by tusbar** [comment]
```
{ inputType: 'url',
  url: 'http://bano.openstreetmap.fr/data/bano-80.csv',
  statusCode: 200,
  redirectUrls: [],
  finalUrl: 'http://bano.openstreetmap.fr/data/bano-80.csv',
  etag: '"ea09db-e8e05d-5704a1120365f"',
  lastModified: 'Fri, 06 Jul 2018 00:51:40 GMT',
  fileName: 'bano-80.csv',
  fileTypes:
   [ { ext: 'csv', mime: 'text/csv', source: 'url:content-type' },
     { ext: 'csv', mime: 'text/csv', source: 'url:filename' } ],
  temporary: '/var/folders/wb/4xx5dj9j0r12lym3mgxhj0l00000gn/T/plunger_cwNpdz',
  type: 'file',
  warning: 'Did not receive any data from the server for 4000ms',
  analyzed: true }
```
